version: 2
jobs:           
  build:
    working_directory: ~/myapp
    docker:
      - image: circleci/python:3.9.5
    environment:
      AWS_DEFAULT_REGION: ap-northeast-1
    steps:         
      - checkout
      - setup_remote_docker
      - run:
          command: python -m venv env
      - run:
          name: Build Docker Image and Push to ECR
          command: |
            cd ~/myapp
            docker build -t forward-proxy .
      - run:
          name: Install trivy
          command: |
            apk add --update-cache --upgrade curl
            curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sh -s -- -b /usr/local/bin
      - run:
          name: Scan the local image with trivy
          command: trivy --exit-code 0 --no-progress forward-proxy
      - run:
          name: Push to ECR
          command: |
            COMMIT_ID=$(echo $CIRCLE_SHA1 | cut -c1-7)
            . env/bin/activate
            pip install -U awscli awsebcli ebi
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws ecr get-login --no-include-email --region ap-northeast-1 | /bin/bash
            cd ~/myapp
            docker tag  forward-proxy:latest $AWS_ACCOUNT_ID.dkr.ecr.ap-northeast-1.amazonaws.com/forward-proxy:latest
            docker push $AWS_ACCOUNT_ID.dkr.ecr.ap-northeast-1.amazonaws.com/forward-proxy:latest

            
            
workflows:
  version: 2
  build:
    jobs:          
      - build:
          filters:
            branches:
              only:               
                - main
                - master
